// Package mocks
// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/IvanChernomyrdin/go-musthave-metrics-tpl/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// MetricsRepo is an autogenerated mock type for the MetricsRepo type
type MetricsRepo struct {
	mock.Mock
}

// GetAll provides a mock function with no fields
func (_m *MetricsRepo) GetAll(ctx context.Context) (map[string]float64, map[string]int64) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 map[string]float64
	var r1 map[string]int64
	if rf, ok := ret.Get(0).(func() (map[string]float64, map[string]int64)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() map[string]float64); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]float64)
		}
	}

	if rf, ok := ret.Get(1).(func() map[string]int64); ok {
		r1 = rf()
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(map[string]int64)
		}
	}

	return r0, r1
}

// GetCounter provides a mock function with given fields: id
func (_m *MetricsRepo) GetCounter(ctx context.Context, id string) (int64, bool) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetCounter")
	}

	var r0 int64
	var r1 bool
	if rf, ok := ret.Get(0).(func(string) (int64, bool)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) int64); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(string) bool); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// GetGauge provides a mock function with given fields: id
func (_m *MetricsRepo) GetGauge(ctx context.Context, id string) (float64, bool) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetGauge")
	}

	var r0 float64
	var r1 bool
	if rf, ok := ret.Get(0).(func(string) (float64, bool)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) float64); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(float64)
	}

	if rf, ok := ret.Get(1).(func(string) bool); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// UpdateMetricsBatch provides a mock function with given fields: metrics
func (_m *MetricsRepo) UpdateMetricsBatch(ctx context.Context, metrics []model.Metrics) error {
	ret := _m.Called(metrics)

	if len(ret) == 0 {
		panic("no return value specified for UpdateMetricsBatch")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func([]model.Metrics) error); ok {
		r0 = rf(metrics)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpsertCounter provides a mock function with given fields: id, delta
func (_m *MetricsRepo) UpsertCounter(ctx context.Context, id string, delta int64) error {
	ret := _m.Called(id, delta)

	if len(ret) == 0 {
		panic("no return value specified for UpsertCounter")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, int64) error); ok {
		r0 = rf(id, delta)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpsertGauge provides a mock function with given fields: id, value
func (_m *MetricsRepo) UpsertGauge(ctx context.Context, id string, value float64) error {
	ret := _m.Called(id, value)

	if len(ret) == 0 {
		panic("no return value specified for UpsertGauge")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, float64) error); ok {
		r0 = rf(id, value)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMetricsRepo creates a new instance of MetricsRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMetricsRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MetricsRepo {
	mock := &MetricsRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
