// Package mocks
// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/IvanChernomyrdin/go-musthave-metrics-tpl/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// MetricsSender is an autogenerated mock type for the MetricsSender type
type MetricsSender struct {
	mock.Mock
}

// SendMetrics provides a mock function with given fields: ctx, metrics
func (_m *MetricsSender) SendMetrics(ctx context.Context, metrics []model.Metrics) error {
	ret := _m.Called(ctx, metrics)

	if len(ret) == 0 {
		panic("no return value specified for SendMetrics")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []model.Metrics) error); ok {
		r0 = rf(ctx, metrics)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMetricsSender creates a new instance of MetricsSender. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMetricsSender(t interface {
	mock.TestingT
	Cleanup(func())
}) *MetricsSender {
	mock := &MetricsSender{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
