// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	model "github.com/IvanChernomyrdin/go-musthave-metrics-tpl/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// MetricsCollector is an autogenerated mock type for the MetricsCollector type
type MetricsCollector struct {
	mock.Mock
}

// Collect provides a mock function with no fields
func (_m *MetricsCollector) Collect() []model.Metrics {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Collect")
	}

	var r0 []model.Metrics
	if rf, ok := ret.Get(0).(func() []model.Metrics); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Metrics)
		}
	}

	return r0
}

// NewMetricsCollector creates a new instance of MetricsCollector. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMetricsCollector(t interface {
	mock.TestingT
	Cleanup(func())
}) *MetricsCollector {
	mock := &MetricsCollector{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
