// Package mocks
// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	model "github.com/IvanChernomyrdin/go-musthave-metrics-tpl/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// Storage is an autogenerated mock type for the Storage type
type Storage struct {
	mock.Mock
}

// Close provides a mock function with no fields
func (_m *Storage) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAll provides a mock function with no fields
func (_m *Storage) GetAll() (map[string]float64, map[string]int64) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 map[string]float64
	var r1 map[string]int64
	if rf, ok := ret.Get(0).(func() (map[string]float64, map[string]int64)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() map[string]float64); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]float64)
		}
	}

	if rf, ok := ret.Get(1).(func() map[string]int64); ok {
		r1 = rf()
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(map[string]int64)
		}
	}

	return r0, r1
}

// GetCounter provides a mock function with given fields: name
func (_m *Storage) GetCounter(name string) (int64, bool) {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for GetCounter")
	}

	var r0 int64
	var r1 bool
	if rf, ok := ret.Get(0).(func(string) (int64, bool)); ok {
		return rf(name)
	}
	if rf, ok := ret.Get(0).(func(string) int64); ok {
		r0 = rf(name)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(string) bool); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// GetGauge provides a mock function with given fields: name
func (_m *Storage) GetGauge(name string) (float64, bool) {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for GetGauge")
	}

	var r0 float64
	var r1 bool
	if rf, ok := ret.Get(0).(func(string) (float64, bool)); ok {
		return rf(name)
	}
	if rf, ok := ret.Get(0).(func(string) float64); ok {
		r0 = rf(name)
	} else {
		r0 = ret.Get(0).(float64)
	}

	if rf, ok := ret.Get(1).(func(string) bool); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// UpdateMetricsBatch provides a mock function with given fields: metrics
func (_m *Storage) UpdateMetricsBatch(metrics []model.Metrics) error {
	ret := _m.Called(metrics)

	if len(ret) == 0 {
		panic("no return value specified for UpdateMetricsBatch")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func([]model.Metrics) error); ok {
		r0 = rf(metrics)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpsertCounter provides a mock function with given fields: name, d
func (_m *Storage) UpsertCounter(name string, d int64) error {
	ret := _m.Called(name, d)

	if len(ret) == 0 {
		panic("no return value specified for UpsertCounter")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, int64) error); ok {
		r0 = rf(name, d)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpsertGauge provides a mock function with given fields: name, v
func (_m *Storage) UpsertGauge(name string, v float64) error {
	ret := _m.Called(name, v)

	if len(ret) == 0 {
		panic("no return value specified for UpsertGauge")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, float64) error); ok {
		r0 = rf(name, v)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewStorage creates a new instance of Storage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *Storage {
	mock := &Storage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
