// Code generated by cmd/reset; DO NOT EDIT.

package memory

import (
	"sync"
)

func (m *MemStorage) Reset() {
	if m == nil {
		return
	}

	m.mu = sync.RWMutex{}
	clear(m.gauges)
	clear(m.counters)
}
